### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by cmtonkinson** [JonGretar/language-salt#2]
Store package settings files in the  settings/  directory instead of  scoped-properties/      Package.loadSettings  /usr/share/atom/resources/app/src/package.js:550:9  unknown>  /usr/share/atom/resources/app/src/package.js:172:43

**Comment by tehmaspc** [comment]
+1

**Comment by johnkeates** [comment]
+1

**Comment by JonGretar** [comment]
Thanks for this. I'm on my Honeymoon but I'll try to take a look at this tonight and publish it.

**Comment by johnkeates** [comment]
It's basically not breaking anything, but Atom does like to complain about it :) Honeymoon comes first!

**Comment by tehmaspc** [comment]
+1 on Honeymoon :) 

Cheers!

**Comment by BattleBrisket** [comment]
> cmtonkinson commented **19 days ago**

That's a helluva honeymoon. I'm jealous.  :wink:

**Comment by JonGretar** [comment]
> That's a helluva honeymoon. I'm jealous.

Yup. 3 months, 7 countries and one pull request. ;)
