### ISSUE TITLE
syntax highlighting for Jinja2 elements in SLS files broken

### ISSUE THREAD

**Issue by abueschel** [JonGretar/language-salt#8]
Since one of the recent Atom and/or package updates, syntax highlighting for Jinja2 elements seems to be broken.

Atom 1.12.5 on macOS 10.12.1 (16B2555)
language-yaml 0.27.1
atom-jinja2 0.5.0
language-salt 0.4.0

What it looks like:

![screen shot 2016-11-21 at 16 25 27](https://cloud.githubusercontent.com/assets/13065401/20488552/bb9dd11c-b007-11e6-8433-418193896b7b.png)

What Jinja2 should look like (works in only in some situations):

![screen shot 2016-11-21 at 16 23 41](https://cloud.githubusercontent.com/assets/13065401/20488610/e969dabe-b007-11e6-8bca-ba51967ab715.png)

Original code example:

```SaltStack
# pkg.latest
# service.running

httpd:
  pkg:
    - installed
    {% if grains['os'] == 'RedHat' or grains['os'] == 'Fedora' or grains['os'] == 'CentOS' %}
    - name: httpd
    {% elif grains['os'] == 'Debian' or grains['os'] == 'Ubuntu'%}
    - name: apache2
    {% elif grains['os'] == 'Gentoo' or grains['os'] == 'Arch' or grains['os'] == 'FreeBSD' %}
    - name: apache
    {% endif %}
  service:
    - running
    {% if grains['os'] == 'Debian' or grains['os'] == 'Ubuntu' or grains['os'] == 'Gentoo' %}
    - name: apache2
    {% endif %}
    - enable: True
    - require:
      - pkg: httpd

date > /tmp/started_apache:
  cmd:
    - wait
    - watch:
      - service: httpd

{#- Comment #}
```

**Comment by bobrik** [comment]
Another example:

![image](https://cloud.githubusercontent.com/assets/89186/22843553/fffa5bf2-ef8e-11e6-8ccb-1472dd4ff8d0.png)

![image](https://cloud.githubusercontent.com/assets/89186/22843565/0c25ba70-ef8f-11e6-83fd-a96ba339745c.png)

**Comment by JonGretar** [comment]
The problem seems to lie in the atom-jinja2 package.
language-salt really just adds the `.sls` extension to the yaml/jinja support in atom-jinja2.
